version: 2
jobs:
  test:  
    docker:
      - image: circleci/golang:1.11
    working_directory: /home/circleci/talisman
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          command: |
              git config --global user.email "talisman@circlieci.com"
              git config --global user.name "Talsiman Build Bot"
      - run:
          working_directory: /home/circleci/talisman
          command: |
            go mod vendor
            go test -v ./...

workflows:
  version: 2
  main:
    jobs:
      - test